language: node_js
node_js:
  - lts/*
install:
  - yarn install # npm ci
script:
  - yarn build
  - cd .vuepress/dist
  - touch CNAME
  - echo dev.hlae.site > CNAME
  - git init
  - git add -A
  - git commit -m 'deploy'
  - git remote add origin git@github.com:One-Studio/One-Studio.github.io.git
  - git push -u --force origin master
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: .vuepress/dist
  github_token: $GITHUB_TOKEN # A token generated on GitHub allowing Travis to push code on you repository. Set in the Travis settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: master