name: auto deploy vuepress

on:
  push:
    branches:
    - master

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: npm ci
    - run: npm run build
          
    - name: Deploy mybells.github.io/master
      uses: peaceiris/actions-gh-pages@v2
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.DEPLOY_ACCESS_TOKEN }}
        EXTERNAL_REPOSITORY: One-Studio/One-Studio.github.io
        PUBLISH_BRANCH: master
        PUBLISH_DIR: .vuepress/dist
      with:
          emptyCommits: false
