name: auto deploy vuepress

on:
  push:
    branches:
    - master

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: npm ci
    - run: npm run build
    
    - name: git settings
      run:  |
         git config --global user.email "438518244@qq.com"
         git config --global user.name "Purp1e"
         cd .vuepress/dist
         
         git init
         git add -A
         git commit -m 'deploy'
         
         cd ../..

                   
    - name: Pushes to another repository
      uses: cpina/github-action-push-to-another-repository@master
      env:
          API_TOKEN_GITHUB: ${{ secrets.DEPLOY_ACCESS_TOKEN }}
      with:
          source-directory: '.vuepress/dist'
          destination-github-username: 'One-Studio'
          destination-repository-name: 'One-Studio.github.io'
          user-email: 438518244@qq.com
