name: auto deploy vuepress

on:
  push:
    branches:
    - master

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: npm ci
    - run: npm run build
          
    - name: Deploy to GitHub Pages
      # You may pin to the exact commit or the version.
      # uses: JamesIves/github-pages-deploy-action@132898c54c57c7cc6b80eb3a89968de8fc283505
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        # Depending on the repository permissions you may need to provide the action with a GitHub personal access token instead of the provided GitHub token in order to deploy. This should be stored as a secret.
        ACCESS_TOKEN: ${{ secrets.DEPLOY_ACCESS_TOKEN }}
        # This is the branch you wish to deploy to, for example gh-pages or docs.
        BRANCH: master
        # The folder in your repository that you want to deploy. If your build script compiles into a directory named build you would put it here. Folder paths cannot have a leading / or ./. If you wish to deploy the root directory you can place a . here.
        FOLDER: .vuepress/dist
        # If you need to customize the commit message for an integration you can do so.
        COMMIT_MESSAGE: Auto Deployed by GitHub Actions
        # Allows you to speicfy a different repository path so long as you have permissions to push to it. This should be formatted like so: JamesIves/github-pages-deploy-action
        REPOSITORY_NAME: One-Studio/One-Studio.github.io
