name: auto deploy vuepress

on:
  push:
    branches:
    - master

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: npm ci
    - run: npm run build
          
    - name: GitHub Pages
      # You may pin to the exact commit or the version.
      # uses: crazy-max/ghaction-github-pages@361b74e73ccac505c7b5bcbff9b7d6cb0510dc4e
      uses: crazy-max/ghaction-github-pages@v2.1.3
      with:
         # GitHub repository where assets will be deployed (default current)
         repo: One-Studio/One-Studio.github.io
         # Git branch where assets will be deployed
         target_branch: master
         # Create incremental commit instead of doing push force
         allow_empty_commit: false
         # Build directory to deploy
         build_dir: .vuepress/dist
         # Commit message
         commit_message: Auto Deployed by GitHub Actions
         # Write the given domain name to the CNAME file
         fqdn: dev.hlae.site
         # Allow Jekyll to build your site
         jekyll: false
      env:
        GH_PAT: ${{ secrets.DEPLOY_ACCESS_TOKEN }}
