name: auto deploy vuepress

on:
  push:
    branches:
    - master

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: npm ci

    - name: git settings
      run:  |
         cd .vuepress/dist
         git clone git@github.com:One-Studio/One-Studio.github.io.git

    - run: npm run build

    - name: commit
      uses: github-actions-x/commit@v2.6
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        push-branch: master
        commit-message: 'Automatically pushed by GitHub Actions'
        rebase: 'true' # pull abd rebase before commit
        force-add: 'true'
        name: Purple-CSGO
        email: 438518244@qq.com
                   
    - name: Pushes to another repository
      uses: cpina/github-action-push-to-another-repository@master
      env:
          API_TOKEN_GITHUB: ${{ secrets.DEPLOY_ACCESS_TOKEN }}
      with:
          source-directory: '.vuepress/dist'
          destination-github-username: 'One-Studio'
          destination-repository-name: 'One-Studio.github.io'
          user-email: 438518244@qq.com
